//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomodachiDrawer.UI.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TomodachiDrawer.UI.Avalonia.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To RP2040!.
        /// </summary>
        public static string Chip_RP2040_ExportButton {
            get {
                return ResourceManager.GetString("Chip_RP2040_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts your image to a uf2 and copies it directly to a connected RP2040. Base firmware must be flashed first!.
        /// </summary>
        public static string Chip_RP2040_ExportButton_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2040_ExportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to .UF2.
        /// </summary>
        public static string Chip_RP2040_ExportUF2Button {
            get {
                return ResourceManager.GetString("Chip_RP2040_ExportUF2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts your image to a .uf2 file for manual transfer. Use this if auto-detection doesn&apos;t find your device..
        /// </summary>
        public static string Chip_RP2040_ExportUF2Button_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2040_ExportUF2Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Base Firmware.
        /// </summary>
        public static string Chip_RP2040_FlashButton {
            get {
                return ResourceManager.GetString("Chip_RP2040_FlashButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the firmware that reads drawing data from the RP2040&apos;s flash..
        /// </summary>
        public static string Chip_RP2040_FlashButton_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2040_FlashButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP2040: Not Found.
        /// </summary>
        public static string Chip_RP2040_StatusNotFound {
            get {
                return ResourceManager.GetString("Chip_RP2040_StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP2040.
        /// </summary>
        public static string Chip_RP2040_TabHeader {
            get {
                return ResourceManager.GetString("Chip_RP2040_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To RP2350!.
        /// </summary>
        public static string Chip_RP2350_ExportButton {
            get {
                return ResourceManager.GetString("Chip_RP2350_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts your image to a uf2 and copies it directly to a connected RP2350. Base firmware must be flashed first!.
        /// </summary>
        public static string Chip_RP2350_ExportButton_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2350_ExportButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to .UF2.
        /// </summary>
        public static string Chip_RP2350_ExportUF2Button {
            get {
                return ResourceManager.GetString("Chip_RP2350_ExportUF2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts your image to a .uf2 file for manual transfer. Use this if auto-detection doesn&apos;t find your device..
        /// </summary>
        public static string Chip_RP2350_ExportUF2Button_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2350_ExportUF2Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Base Firmware.
        /// </summary>
        public static string Chip_RP2350_FlashButton {
            get {
                return ResourceManager.GetString("Chip_RP2350_FlashButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the firmware that reads drawing data from the RP2350&apos;s flash..
        /// </summary>
        public static string Chip_RP2350_FlashButton_Tooltip {
            get {
                return ResourceManager.GetString("Chip_RP2350_FlashButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP2350: Not Found.
        /// </summary>
        public static string Chip_RP2350_StatusNotFound {
            get {
                return ResourceManager.GetString("Chip_RP2350_StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP2350.
        /// </summary>
        public static string Chip_RP2350_TabHeader {
            get {
                return ResourceManager.GetString("Chip_RP2350_TabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary.
        /// </summary>
        public static string ColourMatcher_Arbitrary {
            get {
                return ResourceManager.GetString("ColourMatcher_Arbitrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue:.
        /// </summary>
        public static string ColourToHSVStepsTool_Hue_Label {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_Hue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Hex:.
        /// </summary>
        public static string ColourToHSVStepsTool_RGBHex_Label {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_RGBHex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #RRGGBB.
        /// </summary>
        public static string ColourToHSVStepsTool_RGBHex_Placeholder {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_RGBHex_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation:.
        /// </summary>
        public static string ColourToHSVStepsTool_Saturation_Label {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_Saturation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour to HSV Steps Tool.
        /// </summary>
        public static string ColourToHSVStepsTool_Title {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string ColourToHSVStepsTool_Value_Label {
            get {
                return ResourceManager.GetString("ColourToHSVStepsTool_Value_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Denoising_None {
            get {
                return ResourceManager.GetString("Denoising_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About TomodachiDrawer.
        /// </summary>
        public static string Dialog_About_Title {
            get {
                return ResourceManager.GetString("Dialog_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 4 options for colour matchers.
        ///Euclidean, Redmean, and CieLab work using the Pro modes default palette.
        ///
        ///Arbitrary on the other hands works using the full colour range, selecting colours in-game is slower but you can achieve much better results.
        ///You can tweak the number of colours it has by changing the value to the right of this button.
        ///Try and pick the lowest number that looks good to your standards to minimize draw time.
        ///Less colours means quicker drawing, and more opportunities for the solver t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_ColourMatcherHelp_Message {
            get {
                return ResourceManager.GetString("Dialog_ColourMatcherHelp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Matchers.
        /// </summary>
        public static string Dialog_ColourMatcherHelp_Title {
            get {
                return ResourceManager.GetString("Dialog_ColourMatcherHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Enabling experimental features may induce more common desyncs. Things that are prone to desyncs, but that are desired to be made stable are put here.
        ///Namely, this includes bucket filling dynamic areas on the switch 2.
        ///Only enable this if you are okay with the increased chance of desyncs. Having this disabled does not guarantee it will work, but that is the goal and in 99% of cases it will work..
        /// </summary>
        public static string Dialog_ExperimentalFeatures_Message {
            get {
                return ResourceManager.GetString("Dialog_ExperimentalFeatures_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Features.
        /// </summary>
        public static string Dialog_ExperimentalFeatures_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentalFeatures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error flashing base firmware.
        /// </summary>
        public static string Dialog_FlashFirmwareError_Title {
            get {
                return ResourceManager.GetString("Dialog_FlashFirmwareError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base firmware flashed! You can now use the standard output button to output your images to it!
        ///If this is your first time, its likely flashing red. Simply hold BOOT and plug it back in, or hold BOOT and press reset if you have it..
        /// </summary>
        public static string Dialog_FlashFirmwareSuccess_Message {
            get {
                return ResourceManager.GetString("Dialog_FlashFirmwareSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup in game is fairly straightforward.
        ///- Navigate to the palette house
        ///- Ensure you are on the &quot;advanced&quot; drawing UI
        ///- Ensure your top colour is set to Black (it is by default)
        ///- Set your cursor to the TOP LEFT of where you want the drawing to be.
        ///- Ensure the full area of the canvas that will be drawn is on screen.
        ///
        ///If the canvas is zoomed in, it will cause the cursor to desync as the canvas moves when the cursor gets on the edges. Zooming out fully avoids this.
        ///
        ///If your image is 256x256 or larger, set i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_InGameSetup_Message {
            get {
                return ResourceManager.GetString("Dialog_InGameSetup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game Setup.
        /// </summary>
        public static string Dialog_InGameSetup_Title {
            get {
                return ResourceManager.GetString("Dialog_InGameSetup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Redistributable.
        /// </summary>
        public static string Dialog_MissingVCRuntime_DownloadButton {
            get {
                return ResourceManager.GetString("Dialog_MissingVCRuntime_DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for this program to run, you MUST install the VC Redistributable.
        ///
        ///Click the open link button to install it. If you do not install it, this program will probably crash silently..
        /// </summary>
        public static string Dialog_MissingVCRuntime_Message {
            get {
                return ResourceManager.GetString("Dialog_MissingVCRuntime_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: MISSING LIBRARIES.
        /// </summary>
        public static string Dialog_MissingVCRuntime_Title {
            get {
                return ResourceManager.GetString("Dialog_MissingVCRuntime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string Dialog_OpenImage_FilterAll {
            get {
                return ResourceManager.GetString("Dialog_OpenImage_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Dialog_OpenImage_FilterImages {
            get {
                return ResourceManager.GetString("Dialog_OpenImage_FilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Image.
        /// </summary>
        public static string Dialog_OpenImage_Title {
            get {
                return ResourceManager.GetString("Dialog_OpenImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Link.
        /// </summary>
        public static string Dialog_OpenLink {
            get {
                return ResourceManager.GetString("Dialog_OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open System Settings.
        /// </summary>
        public static string Dialog_OpenSystemSettings {
            get {
                return ResourceManager.GetString("Dialog_OpenSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string Dialog_PermissionDenied_Title {
            get {
                return ResourceManager.GetString("Dialog_PermissionDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save preview .png.
        /// </summary>
        public static string Dialog_SavePreview_Title {
            get {
                return ResourceManager.GetString("Dialog_SavePreview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF2 Firmware Image.
        /// </summary>
        public static string Dialog_SaveUF2_FilterUF2 {
            get {
                return ResourceManager.GetString("Dialog_SaveUF2_FilterUF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .UF2.
        /// </summary>
        public static string Dialog_SaveUF2_Title {
            get {
                return ResourceManager.GetString("Dialog_SaveUF2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For compatibility, you must select a switch version in the dropdown.
        ///
        ///Switch 1 is more prone to desyncs, so this avoids certain things that are particularly prone to desyncing.
        ///Please be aware that even with Switch 1 selected, desyncs are unfortunately expected due to inconsistent and unpredictable lag in the drawing UI..
        /// </summary>
        public static string Dialog_SelectSwitchVersion_Message {
            get {
                return ResourceManager.GetString("Dialog_SelectSwitchVersion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Switch Version.
        /// </summary>
        public static string Dialog_SelectSwitchVersion_Title {
            get {
                return ResourceManager.GetString("Dialog_SelectSwitchVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your RP2040-Zero (or similar) needs two things in its memory (it&apos;s flash):
        ///- The code that reads the instructions to draw your image and pipe it to the switch
        ///- The instructions to draw your image.
        ///
        ///
        ///To connect your device for flashing, hold down the &quot;BOOT&quot; button and plug it in, or hold &quot;BOOT&quot; and press &quot;RESET&quot; while it is connected.
        ///
        ///You only need to flash the code/&quot;firmware&quot; once.
        ///
        ///You then flash the image data onto it for each image, without needing to reflash the firmware.
        ///
        ///When you first install the f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_SetupExplanation_Message {
            get {
                return ResourceManager.GetString("Dialog_SetupExplanation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSP Solver Time Limit refers to how much time is alloted to the TSP solver.
        ///TSP refers to the Travelling Sales Person problem, which is finding the optimal route among a set of points.
        ///This is used to find the optimal path for the pen tool to take while drawing to minimize drawing time.
        ///
        ///For larger images, the TSP solver can take longer to find an optimal route, its also possible it will never even find an optimal route if there is too many points.
        ///For 64x64, 0.5s is generally fine, anything largest you sho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dialog_TSPHelp_Message {
            get {
                return ResourceManager.GetString("Dialog_TSPHelp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSP Solver Time Limit.
        /// </summary>
        public static string Dialog_TSPHelp_Title {
            get {
                return ResourceManager.GetString("Dialog_TSPHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Releases.
        /// </summary>
        public static string Dialog_UpdateAvailable_OpenReleases {
            get {
                return ResourceManager.GetString("Dialog_UpdateAvailable_OpenReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Dialog_UpdateAvailable_Title {
            get {
                return ResourceManager.GetString("Dialog_UpdateAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Time Estimate: {0}.
        /// </summary>
        public static string DrawTimeEstimate_Format {
            get {
                return ResourceManager.GetString("DrawTimeEstimate_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Draw Time Estimate: ???.
        /// </summary>
        public static string DrawTimeEstimate_Initial {
            get {
                return ResourceManager.GetString("DrawTimeEstimate_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a generally very accurate estimate as to how long the drawing will take, including all actions..
        /// </summary>
        public static string DrawTimeEstimate_Tooltip {
            get {
                return ResourceManager.GetString("DrawTimeEstimate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Image.
        /// </summary>
        public static string InputImage_Header {
            get {
                return ResourceManager.GetString("InputImage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string InputImage_OpenButton {
            get {
                return ResourceManager.GetString("InputImage_OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image loaded….
        /// </summary>
        public static string InputImage_PathBox_Placeholder {
            get {
                return ResourceManager.GetString("InputImage_PathBox_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log_Header {
            get {
                return ResourceManager.GetString("Log_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Preview....
        /// </summary>
        public static string Menu_File_SavePreview {
            get {
                return ResourceManager.GetString("Menu_File_SavePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string Menu_Help_CheckForUpdate {
            get {
                return ResourceManager.GetString("Menu_Help_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _In-Game Setup Info.
        /// </summary>
        public static string Menu_Help_InGameSetupInfo {
            get {
                return ResourceManager.GetString("Menu_Help_InGameSetupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open GitHub Repo.
        /// </summary>
        public static string Menu_Help_OpenGitHubRepo {
            get {
                return ResourceManager.GetString("Menu_Help_OpenGitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Setup Explanation.
        /// </summary>
        public static string Menu_Help_SetupExplanation {
            get {
                return ResourceManager.GetString("Menu_Help_SetupExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show Welcome Again.
        /// </summary>
        public static string Menu_Help_ShowWelcomeAgain {
            get {
                return ResourceManager.GetString("Menu_Help_ShowWelcomeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check For Updates On Start.
        /// </summary>
        public static string Menu_Settings_CheckForUpdatesOnStart {
            get {
                return ResourceManager.GetString("Menu_Settings_CheckForUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enable Experimental Features.
        /// </summary>
        public static string Menu_Settings_EnableExperimentalFeatures {
            get {
                return ResourceManager.GetString("Menu_Settings_EnableExperimentalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Telemetry Prompt.
        /// </summary>
        public static string Menu_Settings_OpenTelemetryPrompt {
            get {
                return ResourceManager.GetString("Menu_Settings_OpenTelemetryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme.
        /// </summary>
        public static string Menu_Settings_Theme {
            get {
                return ResourceManager.GetString("Menu_Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark.
        /// </summary>
        public static string Menu_Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Menu_Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        public static string Menu_Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Menu_Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Match System.
        /// </summary>
        public static string Menu_Settings_Theme_MatchSystem {
            get {
                return ResourceManager.GetString("Menu_Settings_Theme_MatchSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Templates.
        /// </summary>
        public static string Menu_Templates {
            get {
                return ResourceManager.GetString("Menu_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Convert Colour to HSV Steps.
        /// </summary>
        public static string Menu_Tools_ConvertColourToHSVSteps {
            get {
                return ResourceManager.GetString("Menu_Tools_ConvertColourToHSVSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Limit:.
        /// </summary>
        public static string Preview_ColourLimit_Label {
            get {
                return ResourceManager.GetString("Preview_ColourLimit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Matcher:.
        /// </summary>
        public static string Preview_ColourMatcher_Label {
            get {
                return ResourceManager.GetString("Preview_ColourMatcher_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Preview_ColourMatcherHelp_Button {
            get {
                return ResourceManager.GetString("Preview_ColourMatcherHelp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denoising:.
        /// </summary>
        public static string Preview_Denoising_Label {
            get {
                return ResourceManager.GetString("Preview_Denoising_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview ({0}x{1}).
        /// </summary>
        public static string Preview_Header_WithSize {
            get {
                return ResourceManager.GetString("Preview_Header_WithSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview_Header {
            get {
                return ResourceManager.GetString("Preview_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Home Canvas To Top Left (Resets canvas).
        /// </summary>
        public static string Routing_AutoHomeCanvas {
            get {
                return ResourceManager.GetString("Routing_AutoHomeCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the beginning, the program will zoom out, and set itself at the very very top left of the canvas. This is automatically checked for full size (256x256) images. Additionally, to ensure the bucket tool works for Switch 2 it will clear the canvas..
        /// </summary>
        public static string Routing_AutoHomeCanvas_Tooltip {
            get {
                return ResourceManager.GetString("Routing_AutoHomeCanvas_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string Routing_Header {
            get {
                return ResourceManager.GetString("Routing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch 1/Lite/OLED.
        /// </summary>
        public static string Routing_Switch1LiteOLED {
            get {
                return ResourceManager.GetString("Routing_Switch1LiteOLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch 2.
        /// </summary>
        public static string Routing_Switch2 {
            get {
                return ResourceManager.GetString("Routing_Switch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT YOUR SWITCH!.
        /// </summary>
        public static string Routing_SwitchComboBox_Placeholder {
            get {
                return ResourceManager.GetString("Routing_SwitchComboBox_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Compatibility:.
        /// </summary>
        public static string Routing_SwitchCompatibility_Label {
            get {
                return ResourceManager.GetString("Routing_SwitchCompatibility_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Routing_TSPHelpButton {
            get {
                return ResourceManager.GetString("Routing_TSPHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSP Solver Time Limit.
        /// </summary>
        public static string Routing_TSPTimeLimitLabel {
            get {
                return ResourceManager.GetString("Routing_TSPTimeLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Routing_TSPTimeLimitSeconds {
            get {
                return ResourceManager.GetString("Routing_TSPTimeLimitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your mind later through the Settings..
        /// </summary>
        public static string TelemetryPrompt_ChangeMindLater {
            get {
                return ResourceManager.GetString("TelemetryPrompt_ChangeMindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous usage data helps me to better understand how the app is used and know where to focus development efforts. No personal data is collected..
        /// </summary>
        public static string TelemetryPrompt_Description {
            get {
                return ResourceManager.GetString("TelemetryPrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s collected?.
        /// </summary>
        public static string TelemetryPrompt_ExpanderHeader {
            get {
                return ResourceManager.GetString("TelemetryPrompt_ExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help improve Tomodachi Drawer?.
        /// </summary>
        public static string TelemetryPrompt_Header {
            get {
                return ResourceManager.GetString("TelemetryPrompt_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your actual images are never uploaded..
        /// </summary>
        public static string TelemetryPrompt_ImagesNeverUploaded {
            get {
                return ResourceManager.GetString("TelemetryPrompt_ImagesNeverUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Thanks.
        /// </summary>
        public static string TelemetryPrompt_NoThanksButton {
            get {
                return ResourceManager.GetString("TelemetryPrompt_NoThanksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Number of colours in the image.
        /// </summary>
        public static string TelemetryPrompt_OnExport_ColourCount {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_ColourCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Image dimensions.
        /// </summary>
        public static string TelemetryPrompt_OnExport_Dimensions {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Draw time estimate.
        /// </summary>
        public static string TelemetryPrompt_OnExport_DrawTimeEstimate {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_DrawTimeEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Whether experimental features are enabled.
        /// </summary>
        public static string TelemetryPrompt_OnExport_ExperimentalEnabled {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_ExperimentalEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an image is exported:.
        /// </summary>
        public static string TelemetryPrompt_OnExport_Header {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Colour quantizer mode and limit.
        /// </summary>
        public static string TelemetryPrompt_OnExport_QuantizerMode {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_QuantizerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Selected Switch version.
        /// </summary>
        public static string TelemetryPrompt_OnExport_SwitchVersion {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_SwitchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - TSP Time Limit.
        /// </summary>
        public static string TelemetryPrompt_OnExport_TSPTimeLimit {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnExport_TSPTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - App version.
        /// </summary>
        public static string TelemetryPrompt_OnStartup_AppVersion {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnStartup_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - CPU architecture.
        /// </summary>
        public static string TelemetryPrompt_OnStartup_CPU {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnStartup_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On startup:.
        /// </summary>
        public static string TelemetryPrompt_OnStartup_Header {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnStartup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   - Operating system and version.
        /// </summary>
        public static string TelemetryPrompt_OnStartup_OS {
            get {
                return ResourceManager.GetString("TelemetryPrompt_OnStartup_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure.
        /// </summary>
        public static string TelemetryPrompt_SureButton {
            get {
                return ResourceManager.GetString("TelemetryPrompt_SureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry Opt-In.
        /// </summary>
        public static string TelemetryPrompt_Title {
            get {
                return ResourceManager.GetString("TelemetryPrompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Telemetry Source Code.
        /// </summary>
        public static string TelemetryPrompt_ViewSourceButton {
            get {
                return ResourceManager.GetString("TelemetryPrompt_ViewSourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TemplateTool_ConfirmButton {
            get {
                return ResourceManager.GetString("TemplateTool_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy template to clipboard..
        /// </summary>
        public static string TemplateTool_CopyClipboardButton {
            get {
                return ResourceManager.GetString("TemplateTool_CopyClipboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image you had on your clipboard was not 256x256. You can copy the template again with the Copy Template To Clipboard button..
        /// </summary>
        public static string TemplateTool_Dialog_ErrorClipboardNotSquare_Message {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_ErrorClipboardNotSquare_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an image on your clipboard. Make sure you copied it..
        /// </summary>
        public static string TemplateTool_Dialog_ErrorNoClipboardImage_Message {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_ErrorNoClipboardImage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image must be 256x256. You can save the template with the Save Template To File button to use as a starting point..
        /// </summary>
        public static string TemplateTool_Dialog_ErrorNotSquare_Message {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_ErrorNotSquare_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TemplateTool_Dialog_ErrorNotSquare_Title {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_ErrorNotSquare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Drawing.
        /// </summary>
        public static string TemplateTool_Dialog_OpenDrawing_Title {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_OpenDrawing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Template.
        /// </summary>
        public static string TemplateTool_Dialog_SaveTemplate_Title {
            get {
                return ResourceManager.GetString("TemplateTool_Dialog_SaveTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TemplateTool_ExitButton {
            get {
                return ResourceManager.GetString("TemplateTool_ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: If you have a non-100% display scale in Windows, you will need to use the Save and Open buttons due to a bug in Avalonia UI that resizes the template when copied. .
        /// </summary>
        public static string TemplateTool_Information_DisplayScaleNote {
            get {
                return ResourceManager.GetString("TemplateTool_Information_DisplayScaleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See GitHub issue..
        /// </summary>
        public static string TemplateTool_Information_DisplayScaleNote_Link {
            get {
                return ResourceManager.GetString("TemplateTool_Information_DisplayScaleNote_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TemplateTool_Information_Header {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected a complex template type..
        /// </summary>
        public static string TemplateTool_Information_Intro {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Paste the image on your clipboard in an image editor of your choice..
        /// </summary>
        public static string TemplateTool_Information_Step1 {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Add whatever content you want to the image. Anything in the opaque area of the template will not be drawn!.
        /// </summary>
        public static string TemplateTool_Information_Step2 {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Once done, click Paste drawing from clipboard (after copying the final version in your editor).
        /// </summary>
        public static string TemplateTool_Information_Step3 {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Press Confirm to return to the main view with this image as the input. This tool will remove all pixels in the undrawable area..
        /// </summary>
        public static string TemplateTool_Information_Step4 {
            get {
                return ResourceManager.GetString("TemplateTool_Information_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to use:.
        /// </summary>
        public static string TemplateTool_Information_StepsHeader {
            get {
                return ResourceManager.GetString("TemplateTool_Information_StepsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open drawing from file....
        /// </summary>
        public static string TemplateTool_OpenDrawingButton {
            get {
                return ResourceManager.GetString("TemplateTool_OpenDrawingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the completed template, must be 256x256..
        /// </summary>
        public static string TemplateTool_OpenDrawingButton_Tooltip {
            get {
                return ResourceManager.GetString("TemplateTool_OpenDrawingButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TemplateTool_Options_Header {
            get {
                return ResourceManager.GetString("TemplateTool_Options_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste drawing from clipboard..
        /// </summary>
        public static string TemplateTool_PasteButton {
            get {
                return ResourceManager.GetString("TemplateTool_PasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save template to file....
        /// </summary>
        public static string TemplateTool_SaveTemplateButton {
            get {
                return ResourceManager.GetString("TemplateTool_SaveTemplateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the template as a png to file. Use this if you have display scaling screwing up the image resolution (it should be 256x256) - or if you just prefer this way..
        /// </summary>
        public static string TemplateTool_SaveTemplateButton_Tooltip {
            get {
                return ResourceManager.GetString("TemplateTool_SaveTemplateButton_Tooltip", resourceCulture);
            }
        }
    }
}
